### ISSUE TITLE
Refatorar widget class para um novo arquivo

### ISSUE THREAD

**Issue by tiagomso** [rodrigorahman/flutter-dart-utils-vscode#16]
Qual seria o comando para gerar uma classe em novo arquivo de um Widget existente em um determinado arquivo ? Quero separar o código da classe para um novo arquivo.

**Comment by rodrigorahman** [comment]
Não temos esse comando, mas me parece muito interessante, teria como me mandar um exemplo certinho do que você gostaria de fazer?

**Comment by rodrigorahman** [comment]
Fala man blz? A própria extension do flutter já faz isso pra você, selecione o widget que você quer e clique em Extract Widget ;-)
